# ============================================================
#  Setup: route opendraft through LiteLLM at aiangela.cloud
# ============================================================
# Run once from the project root:
#   powershell -ExecutionPolicy Bypass -File .\setup_litellm.ps1
#
# What it does:
#   1. Writes opendraft/.env with the LiteLLM-routed OpenAI provider config
#   2. Backs up any existing opendraft/.env to opendraft/.env.backup.<timestamp>
# ============================================================

$ErrorActionPreference = "Stop"

$ROOT       = (Resolve-Path "$PSScriptRoot").Path
$ENV_PATH   = Join-Path $ROOT "opendraft\.env"
$TIMESTAMP  = Get-Date -Format "yyyyMMddHHmmss"
$BACKUP     = Join-Path $ROOT "opendraft\.env.backup.$TIMESTAMP"

$LITELLM_BASE_URL = "https://litellm.aiangela.cloud/v1"
$LITELLM_API_KEY  = "sk-P5R6uSqsjteUOGAJX6rf0w"
$LITELLM_MODEL    = "gemini-3.1-flash-lite"

Write-Host ""
Write-Host "=== OpenDraft x LiteLLM setup ===" -ForegroundColor Cyan
Write-Host "  Base URL : $LITELLM_BASE_URL"
Write-Host "  Model    : $LITELLM_MODEL"
Write-Host "  Env file : $ENV_PATH"
Write-Host ""

# Backup existing
if (Test-Path $ENV_PATH) {
    Copy-Item $ENV_PATH $BACKUP -Force
    Write-Host "[OK] Existing .env backed up to $BACKUP" -ForegroundColor Yellow
}

# Write new .env
$content = @"
# OpenDraft env - routed through LiteLLM self-hosted at litellm.aiangela.cloud
# Generated by setup_litellm.ps1 on $TIMESTAMP

# --- LLM Provider ---
#   gemini -> google.genai SDK (direct, default)
#   openai -> OpenAI SDK against OPENAI_BASE_URL (LiteLLM / OpenRouter / Ollama / vLLM / ...)
AI_PROVIDER=openai

# --- OpenAI-compatible endpoint (LiteLLM) ---
OPENAI_API_KEY=$LITELLM_API_KEY
OPENAI_BASE_URL=$LITELLM_BASE_URL
OPENAI_MODEL=$LITELLM_MODEL
# Optional: cap output tokens per call (defaults to model's own limit)
# OPENAI_MAX_OUTPUT_TOKENS=8192

# --- Original Gemini direct (kept as fallback, currently unused) ---
# GOOGLE_API_KEY=your-gemini-api-key
# GEMINI_MODEL=gemini-3-flash-preview

# --- Optional alternative providers ---
# ANTHROPIC_API_KEY=your-claude-api-key

# --- Fallback Gemini keys for rate-limit resilience ---
# GOOGLE_API_KEY_FALLBACK=
# GOOGLE_API_KEY_FALLBACK_2=
# GOOGLE_API_KEY_FALLBACK_3=
"@

Set-Content -Path $ENV_PATH -Value $content -Encoding UTF8
Write-Host "[OK] .env written" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  cd backend"
Write-Host "  python -m uvicorn server:app --host 127.0.0.1 --port 8000"
Write-Host ""
Write-Host "Then open http://127.0.0.1:8000 and the chat will route LLM calls through LiteLLM." -ForegroundColor Cyan
Write-Host ""

# Quick smoke test: confirm the LiteLLM key is reachable from this machine
Write-Host "[CHECK] Verifying LiteLLM reachability ..." -ForegroundColor Cyan
try {
    $headers = @{ "Authorization" = "Bearer $LITELLM_API_KEY"; "Content-Type" = "application/json" }
    $body = @{ model = $LITELLM_MODEL; messages = @(@{ role = "user"; content = "ping" }); max_tokens = 5 } | ConvertTo-Json -Depth 4
    $resp = Invoke-RestMethod -Uri "$LITELLM_BASE_URL/chat/completions" -Method Post -Headers $headers -Body $body -TimeoutSec 20
    Write-Host "[OK] LiteLLM responded: $($resp.choices[0].message.content)" -ForegroundColor Green
} catch {
    Write-Host "[WARN] Could not reach LiteLLM right now: $($_.Exception.Message)" -ForegroundColor Yellow
    Write-Host "       The .env is still written - check connectivity when you start the server." -ForegroundColor Yellow
}